# Generated by Django 3.2.15 on 2022-10-27 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_descripton'),
        ('production_lines', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='report',
            name='production_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_lines.productionline'),
        ),
    ]
