# Generated by Django 3.2.15 on 2022-10-28 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_report_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-day',)},
        ),
    ]
