# Generated by Django 3.2.15 on 2022-10-29 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemreported',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
    ]
